### ISSUE TITLE
Does not save the config file in the correct location on the mac.

### ISSUE THREAD

**Issue by dak180** [jrossignol/WaypointManager#22]
it saves it in a file named `\GameData\WaypointManager\WaypointManager.cfg` in the `Kerbal Space Program` directory.

This likely happens on linux too since `\` is only the path separator on windows.

**Comment by jrossignol** [comment]
Ugh, of course the native C# methods wouldn't be platform independent.  I'll have a look and see if I can figure out the proper way to do this.
