### ISSUE TITLE
Breaks multiple things

### ISSUE THREAD

**Issue by swilbur** [jrossignol/WaypointManager#27]
Many functions in vanilla stopped working when I installed this mod.  The "Recover Craft", "Revert Flight", and "Quit to main menu" buttons simply don't do anything when clicked.  Attempting to leave the Tracking Station instead causes the view to zoom out continuously (soon showing only the sun) while the game ignores all further input, so I have to force close the window.  This is using the Steam version of the game on Windows, and the problem occurs with both the 64- and 32-bit executables.

**Comment by jrossignol** [comment]
This normally means an exception occurred - but I need the ksp.log file
before I can do any investigation.

**Comment by swilbur** [comment]
Ah, that was enough information for me to fix it myself.  The exception was:

IsolatedStorageException: Could not find a part of the path "C:\Program Files (x86)\Steam\steamapps\common\Kerbal Space Program\GameData\WaypointManager\WaypointManager.cfg".

I had apparently installed it to "Kerbal Space Program\GameData\GameData\WaypointManager" instead of "Kerbal Space Program\GameData\WaypointManager".  It works fine with that fixed.
