### ISSUE TITLE
Custom icons?

### ISSUE THREAD

**Issue by tyrope** [jrossignol/WaypointManager#32]
I noticed a folder called `\icons\Waypoint` and was sort of hoping one could put custom icons in there (since it was empty to start with) I put a 32x32 PNG image in there, since that's what's used in `\icons\CelestialBodies`, but it doesn't appear to be showing up. Attached below is the image I am using.

![controltower](https://cloud.githubusercontent.com/assets/516490/7382530/5d0c0a66-ee10-11e4-9839-680a29d55e3b.png)

Is this a current feature and am I doing it wrong? If not, will this be a future feature?

**Comment by jrossignol** [comment]
Current feature! There's a cfg file with the directory listed. On my phone
so I can't check right now, but think it is icons/Custom

**Comment by jrossignol** [comment]
You can also add a .cfg file anywhere you want and specify alternate location(s) for custom icons:
```
WAYPOINT_MANAGER_ICONS
{
    name = WaypointManager
    url = WaypointManager/icons/Custom
}
```

**Comment by tyrope** [comment]
Awesome! Thanks for specifying, I notice now that there already is a .cfg file, however it points to `/icons/Custom` which, by default, doesn't exist. Does the mod use the `/icons/waypoints` folder at all? If not, they should probably be merged into 1 feature (either by renaming the folder, or changing the cfg)

**Comment by jrossignol** [comment]
I renamed the folder for the next release.  If any custom icons get introduced as part of Waypoint Manager at any point, that's where they'll go.
