### ISSUE TITLE
Display Waypoint Latitude and Longitude

### ISSUE THREAD

**Issue by DavidShade** [jrossignol/WaypointManager#41]
I would like to have an option to display a Waypoint's Latitude and Longitude for use with MechJeb Landing Guidance and Rover Autopilot. I've made the changes for my personal use, but thought I would throw this out there in case it might be helpful for others as well.

**Comment by jrossignol** [comment]
Sure, if you've made the changes, submit a pull request and I'll look at getting it in the next version.
