### ISSUE TITLE
Waypoint manager did not pick up the second waypoint when it became visible in the contrat window

### ISSUE THREAD

**Issue by linuxgurugamer** [jrossignol/WaypointManager#44]
Waypoint manager did not pick up the second waypoint when it became visible in the contract window.  Also, didn't see the icon anywhere on screen.
This was with the following parameters in the waypoint code:
hidden = true
parameter = completedparm

Also, when I removed the "hidden = true", waypointmanager showed all waypoints.  Sample waypoint is below:

		RANDOM_WAYPOINT_NEAR
		{
			name = @/a2
			icon = report
			parameter = Location1AllObjectives
			hidden = true			
			altitude = 0.0
			waterAllowed = false
			nearIndex = 0
			count = 1
			minDistance = Prestige() == Trivial ? @/TrivialMin : Prestige() == Significant ? @/SignificantMin : @/ExceptionalMin
			maxDistance = Prestige() == Trivial ? @/TrivialMax : Prestige() == Significant ? @/SignificantMax : @/ExceptionalMax

**Comment by jrossignol** [comment]
Does it show up in the map view? if it doesn't, then this isn't a Waypoint
Manager issue.

**Comment by linuxgurugamer** [comment]
Yes, it does, so what issue would it be?

**Comment by linuxgurugamer** [comment]
I checked the map when testing without the hidden = true, and all 5 waypoints showed up there as well as in waypoint manager.  But not in either of the contract windows

**Comment by jrossignol** [comment]
Contracts window shows parameters, the waypoints are generated by the
behaviour - so whether it is showing in the contract window is not relevant
to waypoint manager.

**Comment by linuxgurugamer** [comment]
ok.  I restored the "hidden = true" ,and both contract windows are working properly
But, the original issue is still there.  Only the first waypoint shows up in WaypointManager, and I checked the map, only one is there.

**Comment by linuxgurugamer** [comment]
Here is a screenshot showing the contract windows and the waypoint manager.
Note that the waypoint called "Blaze" was reached, and after I did the science, the next one called "Gragment" showed up in the contract windows, but not in the waypoint manager
https://www.dropbox.com/s/5eihih4dvno7yf4/screenshot_2015-12-30--16-32-08.png?dl=0
I went back to the space center, and then back to the flight view, no change

**Comment by linuxgurugamer** [comment]
Closing this since I'm pretty sure it is in CC, see my forum posting
