### ISSUE TITLE
bad forum link in WaypointManager.netkan

### ISSUE THREAD

**Issue by miki-g** [jrossignol/WaypointManager#53]

**Comment by jrossignol** [comment]
It's a problem with the backwards compatibility on KSP's forums.  I'm
waiting/hoping that Squad fixes it - otherwise I have to update a dozen
.netkan files, and a bunch of other places (so I don't want to even try
unless I know I have no other choice).

**Comment by jrossignol** [comment]
Okay had to manually do updates, but this is now in the process of being fixed. See https://github.com/KSP-CKAN/NetKAN/pull/6377 for more info.
