### ISSUE TITLE
Version 2.7.5: having exception on every scene change

### ISSUE THREAD

**Issue by DomiKamu** [jrossignol/WaypointManager#57]
Hi,
I've tried v2.7.5 because I assume your mod as very useful!
However I report exceptions (Null Reference) on every scene change.
**KSP.log** enclosed (renamed as .log.txt here).

[KSP.log.txt](https://github.com/jrossignol/WaypointManager/files/2823953/KSP.log.txt)

KSP v1.6.1 x64 (Windows), no other mod installed, except "Making History Expansion DLC" v1.6.1 and ModuleManager v4.0.1 (not used by Waypoint Manager).

Regards,
Dominique.

**Comment by DomiKamu** [comment]
ADDED: Hi, doing some investigations... I've discovered today this exception will be triggered as soon as I install Kopernicus (1.6.1-1 or lastest 1.6.1-2) together with ModularFlightIntegrator v1.2.6.0 (required by Kopernicus). Now I'm using MM v4.0.2. But without Kopernicus, I don't get this exception.

**Comment by jrossignol** [comment]
Unfortunately, your exception doesn't give me much to go off of.  I suspect that it's timing related due to the way I had to hack in the duplicate removal on scene change.  I'll try to have a look in the next couple days and see if I can fix it.

**Comment by DomiKamu** [comment]
Don't worry, it's not urgent (believe me), we're developers for free products (you for KSP, me for VCV Rack), so take the time you'll need.

Note: rossignol is a French common name (designing category of bird). Have a nice weekend and see you soon later.

Dominique (55 yrs old French guy ;).

**Comment by jrossignol** [comment]
I disappeared for 8 months, but now this bug is fixed. :)
