### ISSUE TITLE
Waypoint Manager 2.7.5 shows Dessert Airfield with launch site icon in Waypoint window

### ISSUE THREAD

**Issue by Jacke4913** [jrossignol/WaypointManager#58]
Windows 10 1803 Home
KSP 1.6.1 with Making History
Waypoint Manager 2.7.5

As title says, the Dessert Airfield has the launch site icon in the Waypoint Window.

Screenshot in Tracking Station
https://i.imgur.com/o62gtTl.png

Screenshot in Flight mode
https://i.imgur.com/FyLE3y3.png

**Comment by jrossignol** [comment]
I shouldn't be setting the icons at all - so this is more than likely a stock bug.  If I'm not mistaken, you should be able to see the waypoint icons in either the tracking station or map views and confirm it there without Waypoint Manager installed.

**Comment by Jacke4913** [comment]
I did some checking with stock KSP alone and again with just Waypoint Manager added.  Stock doesn't have the problem, as can be seen in the screenshots below.  I couldn't figure out where the site icons are in the directory tree, but I'm guessing it's not an icon setting problem.  I think you just reference the wrong icon for the Dessert Airfield, maybe referencing the one for the Dessert LaunchPad twice?

Tracking Station
https://i.imgur.com/C5jFuok.png

Map view
https://i.imgur.com/ARRRH1k.png

Map view with names revealed by hovering mouse
https://i.imgur.com/dKxi6Ib.png

Tracking Station took a bit of work to understand.  Look at the ghosted icons for Woomerang in the NW and the Island Airfield in the E.  The Dessert site has both of them close together, which is what it should have.

Here's the same screenshots in a run with Waypoint Manager.

Tracking Station
https://i.imgur.com/dcOsqdX.png

Map view
https://i.imgur.com/syZwmbd.png

Map view with names revealed by hovering mouse
https://i.imgur.com/PnjZx1R.png

And the view from the Dessert Launchpad, with both icons in site.
https://i.imgur.com/dapJBam.png

Note that in the Tracking Station and Map screenshots, the map icons provided by stock appear correct while the ones in the Waypoint Manager have the wrong icon for the Dessert Airfield.

**Comment by jrossignol** [comment]
Confirmed - it's a stock bug.  The icon for the site (what you're seeing on the map) and the icon for the waypoint are two different things.  It's just set incorrectly in stock, but there's no way to display it in stock (so the bug can only be observed through Waypoint Manager).

**Comment by Jacke4913** [comment]
Thanks for dealing with this as best you could.
